# Generated by Django 4.2.1 on 2023-06-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
